minor changes, mostly sudo
lauraweindorf/enigma-dev-x pull request #11
Opened 2020-04-20 19:52 UTC by DerekfromMadison

added sudo to many of the commands

2020-04-20 23:01 UTC, ainsleys commented
@levackt can you review? I'm not sure if sudo will be required for all users so just want to double check if that's best practice. Other changes for clarity are excellent, and very much appreciated @DerekfromMadison ! Thank you!

2020-04-21 04:05 UTC, levackt commented
Thanks @DerekfromMadison !

On sudo, check out the [Docker Post-installation steps](https://docs.docker.com/engine/install/linux-postinstall/), essentially adding your user to the docker group, then you can do without sudo.

2020-04-21 06:04 UTC, reuvenpo requested changes

2020-04-21 06:04 UTC, reuvenpo commented on README.md
> +4.. Install cargo generate
I'd write something like:
>Run `cargo install cargo-generate`

2020-04-21 06:04 UTC, reuvenpo commented on README.md
> +3. If using linux, install build dependency
>If using linux, install the standard build tools:

2020-04-21 07:48 UTC, levackt approved these changes

2020-04-21 07:49 UTC, merged